# dubbo 订阅配置
dubbo:
  cloud:
    # 需要远程调用的服务 多个用逗号分割
    subscribed-services: ruoyi-file

# swagger配置
swagger:
  title: 系统模块接口文档

spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}
        # 从库数据源
        slave:
          lazy: true
          driver-class-name:
          url:
          username:
          password:
